name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./apps/web
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          # Additional environment variables for build
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_b3B0aW11bS1yb29zdGVyLTc3LmNsZXJrLmFjY291bnRzLmRldiQ
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: charliearmstrongdev
          SENTRY_PROJECT: charliearmstrongdev
          NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ secrets.GA_TRACKING_ID }}
          NEXT_PUBLIC_LOGROCKET_APP_ID: ${{ secrets.NEXT_PUBLIC_LOGROCKET_APP_ID }}
          LOGROCKET_RELEASE_VERSION: ${{ secrets.LOGROCKET_RELEASE_VERSION }}